/* =====================================================================
   PHYSICS_LAWS — shared data for the library cards and detail pages.
   Each law has a slug (used in law.html?id=slug), full detail text,
   formula breakdown, real-world examples, and an `anim` id that maps
   to an animation function in law.js.
   ===================================================================== */
window.PHYSICS_LAWS = [
  {
    slug: "newtons-first-law",
    name: "Newton's First Law",
    by: "Isaac Newton",
    year: "1687",
    tag: "Mechanics · Dynamics",
    short: "An object stays at rest or in uniform motion unless acted on by a net external force.",
    statement: "Every object continues in its state of rest, or of uniform motion in a straight line, unless compelled to change that state by a net external force acting on it.",
    eq: "ΣF = 0 ⟹ v = constant",
    vars: [
      { sym: "ΣF", meaning: "the net (total) external force on the object" },
      { sym: "v", meaning: "the object's velocity (speed and direction)" },
    ],
    details: [
      "Also called the <strong>Law of Inertia</strong>. Inertia is the natural tendency of any object to resist a change in its motion. The more mass an object has, the more inertia it has — which is why it is harder to start, stop, or turn a loaded truck than an empty bicycle.",
      "Before Newton, people assumed that a moving object naturally slows down and stops. Newton realised that objects only slow down because of forces like friction and air resistance. Remove those forces — as in deep space — and a moving object keeps gliding forever at the same speed in the same direction.",
      "The key word is <em>net</em> force. Many forces can act at once; if they perfectly cancel out, the object behaves as if no force acts at all and its velocity stays constant.",
    ],
    examples: [
      "A puck slides across smooth ice almost forever because friction is tiny.",
      "Passengers lurch forward when a car brakes suddenly — their bodies want to keep moving.",
      "A spacecraft cruises between planets with its engines off, coasting on inertia.",
    ],
    controls: [
      { id: "v", label: "Speed", min: 0.5, max: 6, step: 0.1, value: 2.2, unit: " m/s" },
    ],
    anim: "inertia",
  },
  {
    slug: "newtons-second-law",
    name: "Newton's Second Law",
    by: "Isaac Newton",
    year: "1687",
    tag: "Mechanics · Dynamics",
    short: "The net force on a body equals its mass times its acceleration.",
    statement: "The acceleration of an object is directly proportional to the net force acting on it and inversely proportional to its mass, and is in the same direction as the net force.",
    eq: "F = m · a",
    vars: [
      { sym: "F", meaning: "net force, measured in newtons (N)" },
      { sym: "m", meaning: "mass of the object, in kilograms (kg)" },
      { sym: "a", meaning: "acceleration, in metres per second squared (m/s²)" },
    ],
    details: [
      "This law turns the idea of force into something we can measure. Push an object with a known force and watch how quickly it speeds up — that is its acceleration.",
      "Two relationships are hidden in <code>F = m·a</code>. For a fixed mass, doubling the force doubles the acceleration. For a fixed force, doubling the mass halves the acceleration. A heavy object is simply harder to get moving.",
      "It also explains weight: gravity pulls every mass with the same acceleration <code>g</code> (about 9.8 m/s²), so your weight is just <code>F = m·g</code>.",
    ],
    examples: [
      "A loaded shopping trolley needs a much bigger push to accelerate than an empty one.",
      "Rockets burn fuel to create a huge force, accelerating an enormous mass.",
      "A cricket ball accelerates fast off the bat because its mass is small.",
    ],
    controls: [
      { id: "force", label: "Force", min: 0, max: 80, step: 1, value: 30, unit: " N" },
      { id: "mass", label: "Mass", min: 1, max: 12, step: 1, value: 3, unit: " kg" },
    ],
    anim: "cart",
  },
  {
    slug: "newtons-third-law",
    name: "Newton's Third Law",
    by: "Isaac Newton",
    year: "1687",
    tag: "Mechanics · Dynamics",
    short: "For every action there is an equal and opposite reaction.",
    statement: "For every action there is an equal and opposite reaction. When one body exerts a force on a second body, the second body exerts a force equal in magnitude and opposite in direction on the first.",
    eq: "F₁₂ = −F₂₁",
    vars: [
      { sym: "F₁₂", meaning: "force that body 1 exerts on body 2" },
      { sym: "F₂₁", meaning: "force that body 2 exerts back on body 1" },
    ],
    details: [
      "Forces always come in pairs. You cannot push on something without it pushing back on you with exactly the same strength in the opposite direction.",
      "The two forces act on <em>different</em> objects, which is why they don't simply cancel out. When you step off a small boat, you push the boat backwards and the boat pushes you forwards.",
      "This is the principle behind all propulsion. A rocket throws hot gas downwards, and the gas pushes the rocket upwards with an equal force.",
    ],
    examples: [
      "A swimmer pushes water backwards; the water pushes the swimmer forwards.",
      "A gun recoils into the shoulder as it fires a bullet forwards.",
      "When you jump, you push the Earth down and it pushes you up.",
    ],
    controls: [
      { id: "mA", label: "Mass of cart A", min: 1, max: 8, step: 1, value: 2, unit: " kg" },
      { id: "mB", label: "Mass of cart B", min: 1, max: 8, step: 1, value: 2, unit: " kg" },
    ],
    anim: "recoil",
  },
  {
    slug: "law-of-gravitation",
    name: "Newton's Law of Gravitation",
    by: "Isaac Newton",
    year: "1687",
    tag: "Mechanics · Gravity",
    short: "Every mass attracts every other mass with a force that grows with mass and weakens with distance.",
    statement: "Every particle of matter attracts every other particle with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centres.",
    eq: "F = G · m₁m₂ / r²",
    vars: [
      { sym: "F", meaning: "gravitational force of attraction" },
      { sym: "G", meaning: "gravitational constant, 6.674 × 10⁻¹¹ N·m²/kg²" },
      { sym: "m₁, m₂", meaning: "the two masses" },
      { sym: "r", meaning: "distance between their centres" },
    ],
    details: [
      "The same force that makes an apple fall holds the Moon in orbit around the Earth and the Earth around the Sun. Newton's insight was that gravity is universal — it acts between all masses, everywhere.",
      "Because of the <code>r²</code> in the denominator, gravity weakens quickly with distance. Move twice as far apart and the force becomes four times weaker; three times as far, nine times weaker.",
      "Gravity is actually a very weak force — you only feel it because the Earth is enormously massive. Two everyday objects attract each other far too weakly to notice.",
    ],
    examples: [
      "The Moon orbits the Earth, held by gravity instead of flying off in a straight line.",
      "Ocean tides rise and fall under the Moon's gravitational pull.",
      "Satellites stay in orbit by balancing their speed against Earth's gravity.",
    ],
    controls: [
      { id: "mass", label: "Star mass", min: 1, max: 10, step: 0.5, value: 5, unit: "×" },
      { id: "dist", label: "Orbit size", min: 120, max: 250, step: 5, value: 230, unit: " px" },
    ],
    anim: "orbit",
  },
  {
    slug: "ohms-law",
    name: "Ohm's Law",
    by: "Georg Ohm",
    year: "1827",
    tag: "Electricity",
    short: "Current through a conductor is proportional to the voltage across it.",
    statement: "The current flowing through a conductor between two points is directly proportional to the voltage across the two points, provided the temperature remains constant.",
    eq: "V = I · R",
    vars: [
      { sym: "V", meaning: "voltage (potential difference), in volts (V)" },
      { sym: "I", meaning: "current, in amperes (A)" },
      { sym: "R", meaning: "resistance, in ohms (Ω)" },
    ],
    details: [
      "Voltage is the 'push' that drives charge through a wire; current is how much charge actually flows; resistance is how much the material fights that flow.",
      "Increase the voltage and more current flows. Increase the resistance and less current flows. Resistance is like the narrowness of a pipe — a thin pipe lets less water through for the same pressure.",
      "Ohm's law is the foundation of circuit design. It lets engineers choose resistor values to set exactly the current they want in a circuit.",
    ],
    examples: [
      "A dimmer switch adds resistance to lower the current and dim a bulb.",
      "Thicker wires have less resistance, so they carry large currents without overheating.",
      "Phone chargers regulate voltage and resistance to deliver a safe current.",
    ],
    controls: [
      { id: "volt", label: "Voltage", min: 0, max: 24, step: 0.5, value: 12, unit: " V" },
      { id: "res", label: "Resistance", min: 1, max: 24, step: 1, value: 6, unit: " Ω" },
    ],
    anim: "circuit",
  },
  {
    slug: "hookes-law",
    name: "Hooke's Law",
    by: "Robert Hooke",
    year: "1678",
    tag: "Elasticity",
    short: "The extension of a spring is proportional to the force stretching it.",
    statement: "Within the elastic limit, the extension of a spring is directly proportional to the force applied to stretch it.",
    eq: "F = k · x",
    vars: [
      { sym: "F", meaning: "force applied to the spring" },
      { sym: "k", meaning: "spring constant (stiffness), in N/m" },
      { sym: "x", meaning: "extension — how far the spring stretches" },
    ],
    details: [
      "Pull a spring twice as hard and it stretches twice as far — as long as you don't overstretch it past its <strong>elastic limit</strong>, beyond which it deforms permanently.",
      "The spring constant <code>k</code> measures stiffness. A stiff spring (large k) barely stretches under load; a soft spring (small k) stretches a lot.",
      "A stretched spring stores elastic potential energy and pulls back with a 'restoring force' that tries to return it to its natural length — the basis of all oscillation.",
    ],
    examples: [
      "Bathroom scales use a spring that compresses in proportion to your weight.",
      "Car suspension springs absorb bumps and push back smoothly.",
      "A trampoline stretches further the harder you land on it.",
    ],
    controls: [
      { id: "k", label: "Spring constant k", min: 5, max: 60, step: 1, value: 20, unit: " N/m" },
      { id: "mass", label: "Mass", min: 0.5, max: 6, step: 0.5, value: 2, unit: " kg" },
    ],
    anim: "spring",
  },
  {
    slug: "conservation-of-energy",
    name: "Conservation of Energy",
    by: "Classical Mechanics",
    year: "1840s",
    tag: "Energy",
    short: "Energy can never be created or destroyed, only transformed.",
    statement: "Energy can neither be created nor destroyed; it can only be transformed from one form to another. The total energy of an isolated system remains constant.",
    eq: "E_total = KE + PE = constant",
    vars: [
      { sym: "E_total", meaning: "total mechanical energy" },
      { sym: "KE", meaning: "kinetic energy — energy of motion (½mv²)" },
      { sym: "PE", meaning: "potential energy — stored energy (mgh)" },
    ],
    details: [
      "Energy is never lost — it just changes form. A swinging pendulum constantly trades height (potential energy) for speed (kinetic energy) and back again, while the total stays the same.",
      "At the top of its swing the pendulum is momentarily still: all of its energy is potential. At the bottom it moves fastest: all of its energy is kinetic. Everywhere in between it is a mix that always adds up to the same total.",
      "In the real world some energy leaks away as heat and sound through friction, so a real pendulum slowly stops — but that energy isn't destroyed, it has simply spread out into the surroundings.",
    ],
    examples: [
      "A roller coaster trades height for speed as it climbs and dives.",
      "A hydroelectric dam turns the potential energy of high water into electricity.",
      "A bouncing ball converts kinetic to elastic to potential energy and back.",
    ],
    controls: [
      { id: "amp", label: "Swing angle", min: 10, max: 80, step: 1, value: 55, unit: "°" },
    ],
    anim: "energy",
  },
  {
    slug: "conservation-of-momentum",
    name: "Conservation of Momentum",
    by: "Classical Mechanics",
    year: "1668",
    tag: "Mechanics",
    short: "In a closed system, total momentum stays constant.",
    statement: "In a closed system with no external forces, the total momentum before an interaction equals the total momentum after it.",
    eq: "m₁u₁ + m₂u₂ = m₁v₁ + m₂v₂",
    vars: [
      { sym: "m", meaning: "mass of each object" },
      { sym: "u", meaning: "velocity before the collision" },
      { sym: "v", meaning: "velocity after the collision" },
    ],
    details: [
      "Momentum is mass times velocity. When objects collide, momentum can pass from one to another, but the grand total never changes — it is conserved.",
      "When a moving ball strikes an identical stationary ball head-on, it stops dead and the second ball moves off with the first one's speed. The momentum was handed over completely.",
      "This law works for everything from billiard balls to colliding galaxies, and is what makes a Newton's cradle click back and forth.",
    ],
    examples: [
      "Billiard balls transfer motion on impact.",
      "A Newton's cradle passes momentum through a row of steel balls.",
      "Two ice skaters push apart and glide off in opposite directions.",
    ],
    controls: [
      { id: "m1", label: "Mass of ball 1", min: 1, max: 8, step: 1, value: 2, unit: " kg" },
      { id: "m2", label: "Mass of ball 2", min: 1, max: 8, step: 1, value: 2, unit: " kg" },
      { id: "u1", label: "Speed of ball 1", min: 1, max: 5, step: 0.5, value: 3, unit: " m/s" },
    ],
    anim: "collision",
  },
  {
    slug: "coulombs-law",
    name: "Coulomb's Law",
    by: "Charles-Augustin de Coulomb",
    year: "1785",
    tag: "Electricity",
    short: "The force between two charges grows with charge and weakens with distance.",
    statement: "The electrostatic force between two point charges is directly proportional to the product of the charges and inversely proportional to the square of the distance between them.",
    eq: "F = k · q₁q₂ / r²",
    vars: [
      { sym: "F", meaning: "electrostatic force between the charges" },
      { sym: "k", meaning: "Coulomb's constant, 8.99 × 10⁹ N·m²/C²" },
      { sym: "q₁, q₂", meaning: "the two electric charges, in coulombs (C)" },
      { sym: "r", meaning: "distance between the charges" },
    ],
    details: [
      "Coulomb's law for electric charge looks just like Newton's law for gravity — but with a twist: charges can <em>repel</em> as well as attract. Like charges (+ and +, or − and −) push apart; opposite charges (+ and −) pull together.",
      "Like gravity, the force follows an inverse-square rule: double the distance and the force drops to a quarter.",
      "This force binds electrons to atomic nuclei and holds molecules together — it is the force behind all of chemistry and electricity.",
    ],
    examples: [
      "A rubbed balloon sticks to a wall by attracting opposite charges.",
      "Static cling makes clothes stick together out of the dryer.",
      "Electrons are held in orbit around an atom's positive nucleus.",
    ],
    controls: [
      { id: "q1", label: "Charge 1 (sign + size)", min: -3, max: 3, step: 1, value: 2, unit: " C" },
      { id: "q2", label: "Charge 2 (sign + size)", min: -3, max: 3, step: 1, value: 2, unit: " C" },
    ],
    anim: "charges",
  },
  {
    slug: "boyles-law",
    name: "Boyle's Law",
    by: "Robert Boyle",
    year: "1662",
    tag: "Gases · Thermodynamics",
    short: "At constant temperature, gas pressure is inversely proportional to its volume.",
    statement: "For a fixed amount of gas at constant temperature, the pressure of the gas is inversely proportional to its volume.",
    eq: "P · V = constant",
    vars: [
      { sym: "P", meaning: "pressure of the gas" },
      { sym: "V", meaning: "volume the gas occupies" },
    ],
    details: [
      "Squeeze a gas into half the space and its pressure doubles. The gas molecules have less room, so they hit the container walls twice as often.",
      "Because the product <code>P × V</code> stays constant, you can predict the new pressure after a change in volume — as long as the temperature doesn't change.",
      "This is why a bicycle pump gets harder to push as you compress the air inside it: shrinking the volume raises the pressure.",
    ],
    examples: [
      "A syringe with its tip blocked gets harder to push as the air compresses.",
      "Your lungs lower their internal pressure by expanding, drawing air in.",
      "A scuba diver's air bubbles expand as they rise and the water pressure drops.",
    ],
    controls: [
      { id: "vol", label: "Volume", min: 20, max: 100, step: 1, value: 70, unit: " %" },
    ],
    anim: "piston",
  },
  {
    slug: "archimedes-principle",
    name: "Archimedes' Principle",
    by: "Archimedes",
    year: "~250 BC",
    tag: "Fluids",
    short: "A submerged body is pushed up by a force equal to the weight of fluid it displaces.",
    statement: "Any object wholly or partially immersed in a fluid is buoyed up by a force equal to the weight of the fluid that the object displaces.",
    eq: "F_buoyant = ρ · V · g",
    vars: [
      { sym: "F_buoyant", meaning: "upward buoyant force" },
      { sym: "ρ", meaning: "density of the fluid" },
      { sym: "V", meaning: "volume of fluid displaced by the object" },
      { sym: "g", meaning: "acceleration due to gravity" },
    ],
    details: [
      "Why do heavy steel ships float? Because they push aside a huge amount of water, and the weight of that displaced water pushes back up hard enough to support the ship.",
      "An object floats when the buoyant force equals its weight, and sinks when its weight is greater. This depends on density: things less dense than water float, denser things sink.",
      "Legend says Archimedes discovered this in his bath and ran into the street shouting 'Eureka!' — he realised he could measure the volume of a crown by the water it displaced.",
    ],
    examples: [
      "A massive steel ship floats by displacing tonnes of water.",
      "A hot-air balloon rises because it displaces heavier surrounding air.",
      "You feel lighter in a swimming pool as water buoys you up.",
    ],
    controls: [
      { id: "density", label: "Object density", min: 0.2, max: 1.6, step: 0.05, value: 0.6, unit: " ×water" },
    ],
    anim: "buoyancy",
  },
  {
    slug: "first-law-thermodynamics",
    name: "First Law of Thermodynamics",
    by: "Thermodynamics",
    year: "1850",
    tag: "Thermodynamics",
    short: "Energy added as heat becomes internal energy plus work done.",
    statement: "The change in the internal energy of a system equals the heat added to the system minus the work done by the system on its surroundings.",
    eq: "ΔU = Q − W",
    vars: [
      { sym: "ΔU", meaning: "change in the system's internal energy" },
      { sym: "Q", meaning: "heat added to the system" },
      { sym: "W", meaning: "work done by the system" },
    ],
    details: [
      "This is conservation of energy applied to heat. Add heat to a gas and that energy has to go somewhere: it either raises the gas's internal energy (making it hotter) or it does work by pushing something — usually both.",
      "When you heat a gas in a cylinder, the gas warms up <em>and</em> expands, pushing a piston outward. The heat you put in is split between these two effects.",
      "This principle is the heart of every engine: burn fuel to add heat, and harness the expanding gas to do useful work.",
    ],
    examples: [
      "A car engine turns the heat of burning fuel into motion.",
      "A pressure cooker traps heat, raising internal energy and pressure.",
      "A steam turbine uses heated steam to push blades and generate power.",
    ],
    controls: [
      { id: "heat", label: "Heat added Q", min: 0, max: 100, step: 1, value: 60, unit: " %" },
    ],
    anim: "thermo",
  },
];
