/* =====================================================================
   MATH_TOPICS — shared data for the Maths library cards & detail pages.
   Same shape as PHYSICS_LAWS: each topic has a slug, statement, formula
   breakdown, examples, controls, and an `anim` id mapping to an animation
   function in animations.js (window.PHYS_ANIM).
   ===================================================================== */
window.MATH_TOPICS = [
  {
    slug: "number-line",
    name: "The Number Line & Integers",
    by: "Arithmetic",
    year: "—",
    tag: "Number",
    short: "Every number has a place on an endless line; adding moves right, subtracting moves left.",
    statement: "The number line places every real number in order on a single line. Adding a positive number moves you to the right, subtracting moves you to the left, and zero sits at the centre between positives and negatives.",
    eq: "a + b   ·   a − b",
    vars: [
      { sym: "a", meaning: "the starting number (your position on the line)" },
      { sym: "b", meaning: "the amount you add (right) or subtract (left)" },
    ],
    details: [
      "The number line turns arithmetic into movement. Start at a number, then hop along: a positive step takes you right toward bigger numbers, a negative step takes you left toward smaller and negative ones.",
      "Crossing zero is where negatives make sense: take 3 and subtract 5, and you land at −2, two steps to the left of zero.",
      "The distance of a number from zero — ignoring its sign — is its <em>absolute value</em>, which is why both +4 and −4 sit four steps from the centre.",
    ],
    examples: [
      "A thermometer is a vertical number line crossing zero into negatives.",
      "A bank balance going overdrawn slips below zero.",
      "Lift floors below ground are labelled with negative numbers.",
    ],
    controls: [
      { id: "a", label: "Start at a", min: -10, max: 10, step: 1, value: 3, unit: "" },
      { id: "b", label: "Add b", min: -10, max: 10, step: 1, value: 5, unit: "" },
    ],
    anim: "m_numberline",
  },
  {
    slug: "pythagoras",
    name: "Pythagorean Theorem",
    by: "Pythagoras",
    year: "~530 BC",
    tag: "Geometry",
    short: "In a right triangle, the square on the longest side equals the sum of the other two squares.",
    statement: "For any right-angled triangle, the area of the square built on the hypotenuse equals the combined areas of the squares built on the two shorter sides.",
    eq: "a² + b² = c²",
    vars: [
      { sym: "a, b", meaning: "the two shorter sides (the legs)" },
      { sym: "c", meaning: "the hypotenuse — the side opposite the right angle" },
    ],
    details: [
      "Build a square on each side of a right triangle and a remarkable thing happens: the two smaller squares, added together, exactly tile the big one. Geometry becomes arithmetic.",
      "Rearranged as c = √(a² + b²), it lets you find any distance from horizontal and vertical steps — the foundation of all coordinate geometry.",
      "Only right-angled triangles obey it exactly; the amount by which a triangle breaks the rule even tells you whether its biggest angle is acute or obtuse.",
    ],
    examples: [
      "A 3-4-5 triangle is the classic builder's check for a true right angle.",
      "Screen sizes use it to turn width and height into a diagonal measurement.",
      "GPS turns north/east offsets into a straight-line distance with it.",
    ],
    controls: [
      { id: "a", label: "Side a", min: 1, max: 8, step: 0.5, value: 3, unit: "" },
      { id: "b", label: "Side b", min: 1, max: 8, step: 0.5, value: 4, unit: "" },
    ],
    anim: "m_pythagoras",
  },
  {
    slug: "unit-circle",
    name: "Trigonometry & the Unit Circle",
    by: "Trigonometry",
    year: "—",
    tag: "Trigonometry",
    short: "Sine and cosine are just the height and width of a point spun around a circle.",
    statement: "On a circle of radius 1, a point at angle θ has coordinates (cos θ, sin θ). As the angle turns, its height traces a sine wave and its width traces a cosine wave.",
    eq: "sin²θ + cos²θ = 1",
    vars: [
      { sym: "θ", meaning: "the angle turned, measured from the positive x-axis" },
      { sym: "cos θ", meaning: "the horizontal coordinate of the point" },
      { sym: "sin θ", meaning: "the vertical coordinate of the point" },
    ],
    details: [
      "Trigonometry starts to make sense the moment you see it as a spinning point. Cosine is how far across the point is, sine is how far up — both swinging smoothly between −1 and +1.",
      "Because the radius is 1, the Pythagorean theorem on those coordinates gives the famous identity sin²θ + cos²θ = 1.",
      "Tracing the height as the angle increases draws the sine wave — the same shape behind sound, light, alternating current, and every oscillation in nature.",
    ],
    examples: [
      "Sound and radio signals are sums of sine waves.",
      "The swing of a pendulum follows a cosine curve.",
      "Engineers describe alternating current with sine functions.",
    ],
    controls: [
      { id: "speed", label: "Rotation speed", min: 0, max: 3, step: 0.1, value: 1, unit: " ×" },
    ],
    anim: "m_unitcircle",
  },
  {
    slug: "linear-functions",
    name: "Linear Functions & Slope",
    by: "Algebra",
    year: "—",
    tag: "Algebra",
    short: "A straight-line graph is set by its slope and where it crosses the y-axis.",
    statement: "A linear function has the form y = mx + c. The slope m is how steeply the line rises (rise over run), and the intercept c is the value of y where the line crosses the vertical axis.",
    eq: "y = m·x + c",
    vars: [
      { sym: "m", meaning: "the slope — vertical rise per unit of horizontal run" },
      { sym: "c", meaning: "the y-intercept, where the line meets the y-axis" },
    ],
    details: [
      "A line is the simplest relationship between two quantities: a constant rate of change. For every step right, you go up by exactly the slope m.",
      "A positive slope climbs, a negative slope falls, and a slope of zero is flat. The steeper the line, the larger the slope's size.",
      "The intercept c just slides the whole line up or down without tilting it — it is the line's value when x is zero.",
    ],
    examples: [
      "A taxi fare = fixed charge (c) plus a rate per mile (m).",
      "A phone plan with a monthly fee plus a cost per gigabyte.",
      "Converting Celsius to Fahrenheit is a straight-line relationship.",
    ],
    controls: [
      { id: "m", label: "Slope m", min: -3, max: 3, step: 0.1, value: 1, unit: "" },
      { id: "c", label: "Intercept c", min: -5, max: 5, step: 0.5, value: 1, unit: "" },
    ],
    anim: "m_linear",
  },
  {
    slug: "quadratics",
    name: "Quadratics & Parabolas",
    by: "Algebra",
    year: "—",
    tag: "Algebra",
    short: "Squaring the variable bends the graph into a U-shaped parabola.",
    statement: "A quadratic function y = ax² + bx + c graphs as a parabola. The coefficient a sets how wide and which way it opens, while b and c shift its position; the roots are where it crosses the x-axis.",
    eq: "y = a·x² + b·x + c",
    vars: [
      { sym: "a", meaning: "controls the width and direction the parabola opens" },
      { sym: "b", meaning: "shifts the curve left or right" },
      { sym: "c", meaning: "the y-intercept" },
    ],
    details: [
      "The moment you square the variable, the straight line bends into a symmetric U — the parabola. A positive a opens it upward, a negative a flips it into a dome.",
      "Larger |a| pinches the curve narrower; small |a| spreads it wide. The lowest (or highest) point is the vertex, sitting on the axis of symmetry.",
      "Where the parabola crosses the x-axis are the roots — the solutions found by the quadratic formula x = (−b ± √(b²−4ac)) / 2a.",
    ],
    examples: [
      "A thrown ball traces a parabola under gravity.",
      "Satellite dishes and headlights use parabolic reflectors to focus.",
      "Profit-versus-price models often peak as a downward parabola.",
    ],
    controls: [
      { id: "a", label: "a (curvature)", min: -2, max: 2, step: 0.1, value: 0.5, unit: "" },
      { id: "b", label: "b (shift)", min: -4, max: 4, step: 0.2, value: 0, unit: "" },
      { id: "c", label: "c (intercept)", min: -4, max: 4, step: 0.5, value: -2, unit: "" },
    ],
    anim: "m_quadratic",
  },
  {
    slug: "circle-geometry",
    name: "The Circle: π, Area & Circumference",
    by: "Geometry",
    year: "—",
    tag: "Geometry",
    short: "Every circle's circumference is π times its diameter, and its area is πr².",
    statement: "For any circle, the circumference equals 2πr and the area equals πr², where r is the radius. The constant π ≈ 3.14159 is the unchanging ratio of any circle's circumference to its diameter.",
    eq: "C = 2πr · A = πr²",
    vars: [
      { sym: "r", meaning: "the radius — centre to edge" },
      { sym: "C", meaning: "the circumference — the distance around" },
      { sym: "A", meaning: "the area enclosed" },
    ],
    details: [
      "Pick any circle, large or small, and divide the distance around it by the distance across it — you always get π. That fixed ratio is one of the deepest constants in mathematics.",
      "Unroll a circle's circumference into a straight line and it measures exactly 2πr — a little over three diameters laid end to end.",
      "The area grows with the <em>square</em> of the radius, so doubling the radius quadruples the area — which is why a large pizza is a far better deal than two smalls.",
    ],
    examples: [
      "A wheel of radius r travels 2πr in one full turn.",
      "Pizza area quadruples when the radius doubles.",
      "Circular pipes are sized by cross-sectional area πr².",
    ],
    controls: [
      { id: "r", label: "Radius r", min: 1, max: 6, step: 0.5, value: 3, unit: "" },
    ],
    anim: "m_circle",
  },
  {
    slug: "derivatives",
    name: "Derivatives: the Slope of a Curve",
    by: "Newton & Leibniz",
    year: "1670s",
    tag: "Calculus",
    short: "The derivative measures how steeply a curve rises at each point — its instant rate of change.",
    statement: "The derivative of a function at a point is the slope of the tangent line there — the instantaneous rate at which the function is changing. It is found as the limit of the slope between two points as they move together.",
    eq: "f′(x) = lim (Δy / Δx)",
    vars: [
      { sym: "f(x)", meaning: "the function (the curve)" },
      { sym: "f′(x)", meaning: "the derivative — the slope at point x" },
      { sym: "tangent", meaning: "the straight line just touching the curve at x" },
    ],
    details: [
      "Average speed is distance over time between two moments. Bring those moments infinitely close together and you get the speed at a single instant — that limiting slope is the derivative.",
      "Geometrically the derivative is the slope of the tangent line: where the curve climbs steeply the derivative is large, where it flattens at a peak or trough the derivative is zero.",
      "Tracking the slope at every point produces a whole new function, the derivative function, which underlies all of motion, optimisation, and change.",
    ],
    examples: [
      "Speed is the derivative of distance with respect to time.",
      "A curve's peaks and valleys occur where its derivative is zero.",
      "Marginal cost is the derivative of total cost in economics.",
    ],
    controls: [
      { id: "x", label: "Point x", min: -3, max: 3, step: 0.05, value: -1, unit: "" },
    ],
    anim: "m_derivative",
  },
  {
    slug: "integration",
    name: "Integration: Area Under a Curve",
    by: "Newton & Leibniz",
    year: "1670s",
    tag: "Calculus",
    short: "An integral adds up infinitely many thin strips to find the area beneath a curve.",
    statement: "The definite integral of a function is the total area between its curve and the axis. It is found by summing the areas of ever-thinner rectangles under the curve, in the limit becoming exact.",
    eq: "∫ f(x) dx  ≈  Σ f(xᵢ)·Δx",
    vars: [
      { sym: "Δx", meaning: "the width of each rectangle strip" },
      { sym: "n", meaning: "the number of strips — more strips, better accuracy" },
      { sym: "∫", meaning: "the integral — the exact total area" },
    ],
    details: [
      "To measure the area under a curved graph, slice it into thin vertical rectangles, find each one's area, and add them up. The answer is close — and gets closer the thinner you slice.",
      "Push the number of strips to infinity and the staircase of rectangles melts onto the curve exactly. That limit is the integral.",
      "Integration is the reverse of differentiation: adding up rates of change recovers the total. Summed speed over time gives distance travelled.",
    ],
    examples: [
      "Total distance is the area under a speed-versus-time graph.",
      "The work done by a varying force is an integral.",
      "Areas of irregular land plots are found by integration.",
    ],
    controls: [
      { id: "n", label: "Number of strips", min: 1, max: 60, step: 1, value: 8, unit: "" },
    ],
    anim: "m_integral",
  },
  {
    slug: "vectors",
    name: "Vectors & Vector Addition",
    by: "Linear Algebra",
    year: "—",
    tag: "Vectors",
    short: "A vector has both size and direction; add two by joining them tip to tail.",
    statement: "A vector carries a magnitude and a direction. Two vectors add by placing the tail of the second at the tip of the first; the resultant runs from the very start to the very end.",
    eq: "a⃗ + b⃗ = R⃗",
    vars: [
      { sym: "a⃗, b⃗", meaning: "the two vectors being added" },
      { sym: "R⃗", meaning: "the resultant — their combined effect" },
    ],
    details: [
      "A plain number can't capture 'go 5 km north-east' — you need a direction too. That's a vector: an arrow whose length is the size and whose heading is the direction.",
      "To add vectors, lay them head to tail: walk along the first, then the second, and the single arrow from your start to your finish is the sum.",
      "The same resultant comes from completing the parallelogram on the two vectors — a picture that explains how forces, velocities, and displacements combine.",
    ],
    examples: [
      "A plane's path is wind velocity added to its own velocity.",
      "Two tug-ropes pulling at angles give a single resultant force.",
      "A boat aiming across a river drifts downstream from the current.",
    ],
    controls: [
      { id: "ax", label: "a → x", min: -6, max: 6, step: 0.5, value: 4, unit: "" },
      { id: "ay", label: "a → y", min: -6, max: 6, step: 0.5, value: 1, unit: "" },
      { id: "bx", label: "b → x", min: -6, max: 6, step: 0.5, value: 1, unit: "" },
      { id: "by", label: "b → y", min: -6, max: 6, step: 0.5, value: 3, unit: "" },
    ],
    anim: "m_vectors",
  },
  {
    slug: "probability",
    name: "Probability",
    by: "Blaise Pascal",
    year: "1654",
    tag: "Probability",
    short: "Probability measures how likely an event is, from 0 (never) to 1 (certain).",
    statement: "The probability of an event is the number of favourable outcomes divided by the total number of equally likely outcomes. Over many trials, the observed frequency settles toward this theoretical value.",
    eq: "P = favourable / total",
    vars: [
      { sym: "P", meaning: "probability, between 0 and 1" },
      { sym: "trials", meaning: "the number of repeats of the experiment" },
    ],
    details: [
      "For a fair die, each of the six faces is equally likely, so each has probability 1/6. Probability simply counts the lucky outcomes against all possible ones.",
      "A single roll is unpredictable, but the <em>law of large numbers</em> says that over thousands of rolls the proportion of each result closes in on its true probability.",
      "Adding two dice shifts the odds: a total of 7 is far likelier than 2, because more combinations produce it — the root of the famous bell-shaped spread.",
    ],
    examples: [
      "A coin flip is 50/50, but ten heads in a row can still happen.",
      "Casinos rely on the law of large numbers to profit over time.",
      "Two dice make 7 the most common total in many board games.",
    ],
    controls: [
      { id: "rate", label: "Rolls per second", min: 1, max: 40, step: 1, value: 12, unit: "" },
    ],
    anim: "m_probability",
  },
  {
    slug: "normal-distribution",
    name: "The Normal Distribution",
    by: "Carl Friedrich Gauss",
    year: "1809",
    tag: "Statistics",
    short: "Many random quantities pile up into a symmetric bell-shaped curve.",
    statement: "When many small independent random effects add up, the results cluster symmetrically around the average in a bell-shaped curve — the normal distribution — with most values near the mean and few far away.",
    eq: "68 % within 1 σ",
    vars: [
      { sym: "μ", meaning: "the mean — the centre of the bell" },
      { sym: "σ", meaning: "the standard deviation — the spread" },
    ],
    details: [
      "Drop balls through a board of pegs and each bounces left or right at random. Astonishingly, the piles that build up at the bottom always form the same bell shape.",
      "That is the normal distribution: lots of small chance effects adding together produce a predictable, symmetric curve centred on the average.",
      "Its spread is measured by the standard deviation σ: about 68% of all values land within one σ of the mean, and 95% within two.",
    ],
    examples: [
      "Human heights cluster around an average in a bell curve.",
      "Repeated measurements scatter normally around the true value.",
      "Exam scores are often scaled assuming a normal spread.",
    ],
    controls: [
      { id: "rate", label: "Ball drop rate", min: 1, max: 12, step: 1, value: 4, unit: "" },
    ],
    anim: "m_normal",
  },
  {
    slug: "exponential-growth",
    name: "Exponential Growth & Logarithms",
    by: "Algebra",
    year: "—",
    tag: "Functions",
    short: "Repeated multiplication explodes upward; logarithms are its mirror inverse.",
    statement: "In exponential growth a quantity multiplies by a fixed factor each step, so it rises ever more steeply. The logarithm is the inverse — it asks what power produces a given number, taming that growth back to a straight line.",
    eq: "y = a·bˣ ⇔ x = log_b(y/a)",
    vars: [
      { sym: "b", meaning: "the growth factor — multiplied each step" },
      { sym: "x", meaning: "the number of steps (the exponent)" },
      { sym: "log", meaning: "the inverse: the power needed to reach a value" },
    ],
    details: [
      "Linear growth adds the same amount each step; exponential growth <em>multiplies</em> by the same factor — and that small difference quickly becomes staggering. Fold paper 42 times and it would reach the Moon.",
      "Anything that grows in proportion to its current size grows exponentially: populations, compound interest, viral spread, and chain reactions.",
      "The logarithm undoes it. Plotting exponential data on a log scale straightens the runaway curve into a tidy line — how we tame earthquakes (Richter) and sound (decibels).",
    ],
    examples: [
      "Compound interest grows your savings exponentially.",
      "A virus spreads exponentially in its early days.",
      "The Richter and decibel scales are logarithmic.",
    ],
    controls: [
      { id: "rate", label: "Growth factor", min: 1, max: 2.2, step: 0.05, value: 1.5, unit: " ×/step" },
    ],
    anim: "m_exponential",
  },
  {
    slug: "fibonacci",
    name: "Fibonacci & the Golden Ratio",
    by: "Leonardo Fibonacci",
    year: "1202",
    tag: "Sequences",
    short: "Each number is the sum of the two before it, and their ratio approaches φ ≈ 1.618.",
    statement: "The Fibonacci sequence starts 1, 1 and makes each new term the sum of the previous two. As the sequence grows, the ratio of consecutive terms closes in on the golden ratio φ ≈ 1.618.",
    eq: "Fₙ = Fₙ₋₁ + Fₙ₋₂",
    vars: [
      { sym: "Fₙ", meaning: "the nth Fibonacci number" },
      { sym: "φ", meaning: "the golden ratio, ≈ 1.61803…" },
    ],
    details: [
      "Begin with 1 and 1, then keep adding the last two: 1, 1, 2, 3, 5, 8, 13, 21… a sequence that appears throughout nature, from sunflower seeds to pinecones.",
      "Divide each number by the one before it and the answer wobbles in, ever closer to a single value: the golden ratio φ ≈ 1.618.",
      "Drawing squares of Fibonacci size and joining their corners with quarter-circles produces the elegant golden spiral seen in shells and galaxies.",
    ],
    examples: [
      "Sunflower seeds and pinecone scales spiral in Fibonacci counts.",
      "The golden ratio appears in art and architecture as a pleasing proportion.",
      "Nautilus shells approximate the golden spiral.",
    ],
    controls: [
      { id: "n", label: "Terms to draw", min: 2, max: 10, step: 1, value: 7, unit: "" },
    ],
    anim: "m_fibonacci",
  },
  {
    slug: "matrix-transformations",
    name: "Matrix Transformations",
    by: "Linear Algebra",
    year: "—",
    tag: "Linear Algebra",
    short: "A 2×2 matrix stretches, rotates and shears the whole plane at once.",
    statement: "A 2×2 matrix maps every point of the plane to a new point, transforming shapes by stretching, rotating, reflecting or shearing them. Its determinant tells you how areas are scaled by the transformation.",
    eq: "[a b ; c d] · v⃗",
    vars: [
      { sym: "a, b, c, d", meaning: "the four entries that define the transformation" },
      { sym: "det", meaning: "the determinant ad − bc — the area scale factor" },
    ],
    details: [
      "A matrix is a machine that takes in a point and spits out a new one. Feed it every point of a square and the whole square is reshaped — all in one consistent operation.",
      "The columns of the matrix show exactly where the two unit arrows (1,0) and (0,1) land; everything else follows from them in straight lines.",
      "The determinant ad − bc measures how much area is stretched or squashed. A negative determinant means the plane has been flipped over.",
    ],
    examples: [
      "Game and graphics engines rotate and scale objects with matrices.",
      "Image editors shear and reflect pictures via transformation matrices.",
      "A determinant of zero collapses the plane onto a line.",
    ],
    controls: [
      { id: "a", label: "a", min: -2, max: 2, step: 0.1, value: 1, unit: "" },
      { id: "b", label: "b", min: -2, max: 2, step: 0.1, value: 0.5, unit: "" },
      { id: "c", label: "c", min: -2, max: 2, step: 0.1, value: 0, unit: "" },
      { id: "d", label: "d", min: -2, max: 2, step: 0.1, value: 1, unit: "" },
    ],
    anim: "m_matrix",
  },
];
